

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Plane003: THREE.Mesh
    Plane005_1: THREE.Mesh
    Plane005_2: THREE.Mesh
    Plane005_3: THREE.Mesh
    Cube002: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
    Plane004_1: THREE.Mesh
    Plane004_2: THREE.Mesh
    Plane006_1: THREE.Mesh
    Plane006_2: THREE.Mesh
    Plane007: THREE.Mesh
    Plane008_1: THREE.Mesh
    Plane008_2: THREE.Mesh
    Plane009_1: THREE.Mesh
    Plane009_2: THREE.Mesh
    Plane010_1: THREE.Mesh
    Plane010_2: THREE.Mesh
    Plane011_1: THREE.Mesh
    Plane011_2: THREE.Mesh
    Plane012_1: THREE.Mesh
    Plane012_2: THREE.Mesh
    Plane013_1: THREE.Mesh
    Plane013_2: THREE.Mesh
    Plane014: THREE.Mesh
    Text: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    window: THREE.MeshStandardMaterial
    ['light bulb']: THREE.MeshStandardMaterial
  }
}
const path = '/city.glb';

export const City = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(path) as GLTFResult;

  const pointRef = useRef<THREE.PointLight>(new THREE.PointLight())

  useEffect(() => {
    materials.window.emissive = new THREE.Color().setRGB(0, 0.95, 0.88);
    materials.window.toneMapped = false;
    materials.window.emissiveIntensity = 4;
    materials.window.needsUpdate = true;

    materials['Material.001'].toneMapped = false;
    materials['Material.001'].needsUpdate = true;
    materials['light bulb'].toneMapped = false;
    materials['light bulb'].needsUpdate = true;


  }, [materials])

  useFrame((state) => {
    if (pointRef.current){
      pointRef.current.intensity = (Math.cos(state.clock.elapsedTime) + 1) / 2;
    }
  })

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Plane001" position={[-1.784, 0.317, -0.757]} />
        <group name="Plane002" position={[-1.345, 0.312, -0.757]} />
        <mesh
          name="Plane003"
          geometry={nodes.Plane003.geometry}
          material={materials['Material.001']}
          position={[-0.147, 0.174, 0]}
        />
        <group name="Plane005" position={[-0.036, 0.174, -1.632]}>
        <pointLight 
                ref={pointRef}
                intensity={1} 
                distance={10}
                position={[0,8.3,0.5]}
                color={'red'}
            />
          <mesh
            name="Plane005_1"
            geometry={nodes.Plane005_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="Plane005_2"
            geometry={nodes.Plane005_2.geometry}
            material={materials.window}
          />
          <mesh
            name="Plane005_3"
            geometry={nodes.Plane005_3.geometry}
            material={materials['light bulb']}
          />
          <mesh
            name="Cube002"
            geometry={nodes.Cube002.geometry}
            material={materials['Material.001']}
            position={[-0.096, 7.98, 0.52]}
            rotation={[0, -0.682, 0]}
            scale={[1.007, 0.249, 1.007]}
          />
          <group name="Plane">
            <mesh
              name="Plane_1"
              geometry={nodes.Plane_1.geometry}
              material={materials['Material.001']}
            />
            <mesh
              name="Plane_2"
              geometry={nodes.Plane_2.geometry}
              material={materials.window}
            />
          </group>
          <group name="Plane004" position={[-0.327, 0.317, 0.875]}>
            <mesh
              name="Plane004_1"
              geometry={nodes.Plane004_1.geometry}
              material={materials['Material.001']}
            />
            <mesh
              name="Plane004_2"
              geometry={nodes.Plane004_2.geometry}
              material={materials.window}
            />
          </group>
          <group name="Plane006" position={[0.216, 0.312, 0.875]}>
            <mesh
              name="Plane006_1"
              geometry={nodes.Plane006_1.geometry}
              material={materials['Material.001']}
            />
            <mesh
              name="Plane006_2"
              geometry={nodes.Plane006_2.geometry}
              material={materials.window}
            />
          </group>
        </group>
        <group name="Cube001" position={[-1.347, 7.653, -1.632]} scale={[1.007, 0.249, 1.007]} />
        <mesh
          name="Plane007"
          geometry={nodes.Plane007.geometry}
          material={materials['Material.001']}
          position={[-0.16, 0.174, 0]}
        />
        <group name="Plane008" position={[0.942, 1.387, 2.584]}>
          <mesh
            name="Plane008_1"
            geometry={nodes.Plane008_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="Plane008_2"
            geometry={nodes.Plane008_2.geometry}
            material={materials.window}
          />
        </group>
        <group name="Plane009" position={[-0.147, 0.161, 2.05]}>
          <mesh
            name="Plane009_1"
            geometry={nodes.Plane009_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="Plane009_2"
            geometry={nodes.Plane009_2.geometry}
            material={materials.window}
          />
        </group>
        <group name="Plane010" position={[-0.901, 1.387, 0.668]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh
            name="Plane010_1"
            geometry={nodes.Plane010_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="Plane010_2"
            geometry={nodes.Plane010_2.geometry}
            material={materials.window}
          />
        </group>
        <group name="Plane011" position={[0.188, 0.161, 1.201]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh
            name="Plane011_1"
            geometry={nodes.Plane011_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="Plane011_2"
            geometry={nodes.Plane011_2.geometry}
            material={materials.window}
          />
        </group>
        <group name="Plane012" position={[-2.448, 0.39, -1.049]} scale={[0.985, 0.97, 1]}>
          <mesh
            name="Plane012_1"
            geometry={nodes.Plane012_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="Plane012_2"
            geometry={nodes.Plane012_2.geometry}
            material={materials.window}
          />
        </group>
        <group name="Plane013" position={[-2.628, 0.39, -1.049]} scale={[0.985, 0.97, 1]}>
          <mesh
            name="Plane013_1"
            geometry={nodes.Plane013_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="Plane013_2"
            geometry={nodes.Plane013_2.geometry}
            material={materials.window}
          />
        </group>
        <mesh
          name="Plane014"
          geometry={nodes.Plane014.geometry}
          material={materials['Material.001']}
          position={[-0.147, 0.174, 0]}
        />
        <mesh
          name="Text"
          geometry={nodes.Text.geometry}
          // material={materials['Material.001']}
          position={[-2.791, 1.098, -1.155]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.218}
        >
          <meshStandardMaterial color={'white'} emissive={[0.589, 0.05, 0.511]} emissiveIntensity={10} toneMapped={false}/>
        </mesh>
      </group>
    </group>
  )
};

useGLTF.preload(path);
